version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: AnimalHouseDB
    volumes:
      - my-db:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

  bot:
    image: api
    restart: always
    depends_on: [db]
    expose:
      - 8080
    ports:
      - 8080:80

volumes:
  my-db: